### ISSUE TITLE
Bug: does not sort vizualizers / visualize sorts

### ISSUE THREAD

**Issue by Gunzinger** [DLadendorfer/SortVizualizer#2]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Clone the SortVizualizer repository
2. Attempt to compile or run the SortVisualizer (404)

### Expected behavior 
The sort should be visualized, or the vizualizers should be sorted.

### Actual behavior 
There is no program.

### Host OS
Windows for Workgroups 3.11
CPU: Intel Mobile Pentium II 300Mhz
RAM: 384MB SDRAM
Video Adapter: NeoMagic Media256AV 2.5MB VRAM

**Comment by JK-F** [comment]
This issue is fixed in a fork already. My Pull Request is still pending @DLadendorfer's approval.
That being said it could take a while seeing the codebase has been undergoing hibernation recently.

**Comment by DLadendorfer** [comment]
I will try to address the issue. The concepting phase has not yet left my brain. Still thinking about over engineering the architecture.

**Comment by DLadendorfer** [comment]
I made some progress on this issue but not enough to close it. Will keep you updated. :)

**Comment by Gunzinger** [comment]
Closing as resolved as the project is now stunningly beautiful and functional (as you are) ❤️

**Comment by DLadendorfer** [comment]
I wouldn't have closed it already. It is missing a few small details and the test coverage is lacking at the moment. Will push towards the "release" and will update the ReadMe accordingly. Thanks anyways. ❤️
